/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as MultiAgentSystemsRouteImport } from './routes/multi-agent-systems'
import { Route as LongMemoryAiSystemsRouteImport } from './routes/long-memory-ai-systems'
import { Route as LlmopsServicesRouteImport } from './routes/llmops-services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GpuPerformanceEngineeringRouteImport } from './routes/gpu-performance-engineering'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiSecurityRouteImport } from './routes/ai-security'
import { Route as AiInfrastructureEngineeringRouteImport } from './routes/ai-infrastructure-engineering'
import { Route as AgentopsServicesRouteImport } from './routes/agentops-services'
import { Route as AgenticAiDevelopmentRouteImport } from './routes/agentic-ai-development'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiAgentSystemsRoute = MultiAgentSystemsRouteImport.update({
  id: '/multi-agent-systems',
  path: '/multi-agent-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const LongMemoryAiSystemsRoute = LongMemoryAiSystemsRouteImport.update({
  id: '/long-memory-ai-systems',
  path: '/long-memory-ai-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmopsServicesRoute = LlmopsServicesRouteImport.update({
  id: '/llmops-services',
  path: '/llmops-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuPerformanceEngineeringRoute =
  GpuPerformanceEngineeringRouteImport.update({
    id: '/gpu-performance-engineering',
    path: '/gpu-performance-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSecurityRoute = AiSecurityRouteImport.update({
  id: '/ai-security',
  path: '/ai-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfrastructureEngineeringRoute =
  AiInfrastructureEngineeringRouteImport.update({
    id: '/ai-infrastructure-engineering',
    path: '/ai-infrastructure-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentopsServicesRoute = AgentopsServicesRouteImport.update({
  id: '/agentops-services',
  path: '/agentops-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticAiDevelopmentRoute = AgenticAiDevelopmentRouteImport.update({
  id: '/agentic-ai-development',
  path: '/agentic-ai-development',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-ai-development': typeof AgenticAiDevelopmentRoute
  '/agentops-services': typeof AgentopsServicesRoute
  '/ai-infrastructure-engineering': typeof AiInfrastructureEngineeringRoute
  '/ai-security': typeof AiSecurityRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/gpu-performance-engineering': typeof GpuPerformanceEngineeringRoute
  '/industries': typeof IndustriesRoute
  '/llmops-services': typeof LlmopsServicesRoute
  '/long-memory-ai-systems': typeof LongMemoryAiSystemsRoute
  '/multi-agent-systems': typeof MultiAgentSystemsRoute
  '/offerings': typeof OfferingsRoute
  '/platform': typeof PlatformRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-ai-development': typeof AgenticAiDevelopmentRoute
  '/agentops-services': typeof AgentopsServicesRoute
  '/ai-infrastructure-engineering': typeof AiInfrastructureEngineeringRoute
  '/ai-security': typeof AiSecurityRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/gpu-performance-engineering': typeof GpuPerformanceEngineeringRoute
  '/industries': typeof IndustriesRoute
  '/llmops-services': typeof LlmopsServicesRoute
  '/long-memory-ai-systems': typeof LongMemoryAiSystemsRoute
  '/multi-agent-systems': typeof MultiAgentSystemsRoute
  '/offerings': typeof OfferingsRoute
  '/platform': typeof PlatformRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-ai-development': typeof AgenticAiDevelopmentRoute
  '/agentops-services': typeof AgentopsServicesRoute
  '/ai-infrastructure-engineering': typeof AiInfrastructureEngineeringRoute
  '/ai-security': typeof AiSecurityRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/gpu-performance-engineering': typeof GpuPerformanceEngineeringRoute
  '/industries': typeof IndustriesRoute
  '/llmops-services': typeof LlmopsServicesRoute
  '/long-memory-ai-systems': typeof LongMemoryAiSystemsRoute
  '/multi-agent-systems': typeof MultiAgentSystemsRoute
  '/offerings': typeof OfferingsRoute
  '/platform': typeof PlatformRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agentic-ai-development'
    | '/agentops-services'
    | '/ai-infrastructure-engineering'
    | '/ai-security'
    | '/blog'
    | '/capabilities'
    | '/case-studies'
    | '/contact'
    | '/gpu-performance-engineering'
    | '/industries'
    | '/llmops-services'
    | '/long-memory-ai-systems'
    | '/multi-agent-systems'
    | '/offerings'
    | '/platform'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/use-cases'
    | '/admin/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agentic-ai-development'
    | '/agentops-services'
    | '/ai-infrastructure-engineering'
    | '/ai-security'
    | '/blog'
    | '/capabilities'
    | '/case-studies'
    | '/contact'
    | '/gpu-performance-engineering'
    | '/industries'
    | '/llmops-services'
    | '/long-memory-ai-systems'
    | '/multi-agent-systems'
    | '/offerings'
    | '/platform'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/use-cases'
    | '/admin/analytics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agentic-ai-development'
    | '/agentops-services'
    | '/ai-infrastructure-engineering'
    | '/ai-security'
    | '/blog'
    | '/capabilities'
    | '/case-studies'
    | '/contact'
    | '/gpu-performance-engineering'
    | '/industries'
    | '/llmops-services'
    | '/long-memory-ai-systems'
    | '/multi-agent-systems'
    | '/offerings'
    | '/platform'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/use-cases'
    | '/admin/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgenticAiDevelopmentRoute: typeof AgenticAiDevelopmentRoute
  AgentopsServicesRoute: typeof AgentopsServicesRoute
  AiInfrastructureEngineeringRoute: typeof AiInfrastructureEngineeringRoute
  AiSecurityRoute: typeof AiSecurityRoute
  BlogRoute: typeof BlogRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  GpuPerformanceEngineeringRoute: typeof GpuPerformanceEngineeringRoute
  IndustriesRoute: typeof IndustriesRoute
  LlmopsServicesRoute: typeof LlmopsServicesRoute
  LongMemoryAiSystemsRoute: typeof LongMemoryAiSystemsRoute
  MultiAgentSystemsRoute: typeof MultiAgentSystemsRoute
  OfferingsRoute: typeof OfferingsRoute
  PlatformRoute: typeof PlatformRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  UseCasesRoute: typeof UseCasesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-agent-systems': {
      id: '/multi-agent-systems'
      path: '/multi-agent-systems'
      fullPath: '/multi-agent-systems'
      preLoaderRoute: typeof MultiAgentSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-memory-ai-systems': {
      id: '/long-memory-ai-systems'
      path: '/long-memory-ai-systems'
      fullPath: '/long-memory-ai-systems'
      preLoaderRoute: typeof LongMemoryAiSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llmops-services': {
      id: '/llmops-services'
      path: '/llmops-services'
      fullPath: '/llmops-services'
      preLoaderRoute: typeof LlmopsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu-performance-engineering': {
      id: '/gpu-performance-engineering'
      path: '/gpu-performance-engineering'
      fullPath: '/gpu-performance-engineering'
      preLoaderRoute: typeof GpuPerformanceEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-security': {
      id: '/ai-security'
      path: '/ai-security'
      fullPath: '/ai-security'
      preLoaderRoute: typeof AiSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-infrastructure-engineering': {
      id: '/ai-infrastructure-engineering'
      path: '/ai-infrastructure-engineering'
      fullPath: '/ai-infrastructure-engineering'
      preLoaderRoute: typeof AiInfrastructureEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentops-services': {
      id: '/agentops-services'
      path: '/agentops-services'
      fullPath: '/agentops-services'
      preLoaderRoute: typeof AgentopsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-ai-development': {
      id: '/agentic-ai-development'
      path: '/agentic-ai-development'
      fullPath: '/agentic-ai-development'
      preLoaderRoute: typeof AgenticAiDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgenticAiDevelopmentRoute: AgenticAiDevelopmentRoute,
  AgentopsServicesRoute: AgentopsServicesRoute,
  AiInfrastructureEngineeringRoute: AiInfrastructureEngineeringRoute,
  AiSecurityRoute: AiSecurityRoute,
  BlogRoute: BlogRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  GpuPerformanceEngineeringRoute: GpuPerformanceEngineeringRoute,
  IndustriesRoute: IndustriesRoute,
  LlmopsServicesRoute: LlmopsServicesRoute,
  LongMemoryAiSystemsRoute: LongMemoryAiSystemsRoute,
  MultiAgentSystemsRoute: MultiAgentSystemsRoute,
  OfferingsRoute: OfferingsRoute,
  PlatformRoute: PlatformRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  UseCasesRoute: UseCasesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
